name: Build

on: [push, pull_request]

jobs:
  winBuild:
    name: 'Windows Build'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build
        shell: cmd
        run: gradlew.bat build
      - uses: actions/upload-artifact@v2
        with:
          name: bin2lang-win64
          path: build/bin/mingwX64/releaseExecutable/bin2lang.exe

  macosBuild:
    name: 'macOS Build'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up AdoptOpenJDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build
        run: ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: bin2lang-macos64
          path: build/bin/macosX64/releaseExecutable/bin2lang.kexe
      - uses: actions/upload-artifact@v2
        with:
          name: bin2lang-linux64
          path: build/bin/linuxX64/releaseExecutable/bin2lang.kexe
